### ISSUE TITLE
Basic UI opsætning af hjemmeside. Navbar etc

### ISSUE THREAD

**Issue by Denduff** [General-Zimmer/SchoolBytes#7]
Header med navigation knapper så man kan komme fra side til side og footer med lidt relavant

**Comment by jakobwulfi** [comment]
![Image](https://github.com/user-attachments/assets/a2c4042a-39a1-4baa-afcb-41bd78ce13cd)

**Comment by jakobwulfi** [comment]
![Image](https://github.com/user-attachments/assets/55cd7cab-9816-4127-b8ed-b9fc332fdbca)

**Comment by General-Zimmer** [comment]
Hej Nikolaj
