### ISSUE TITLE
Fjern bruger fra hold

### ISSUE THREAD

**Issue by Denduff** [General-Zimmer/SchoolBytes#8]
Der skal være en admin funktion for ¨'unsubscribe modal, hvor man kan vælge en participant in select i stedet for at skrive det ind manuelt" 

Vi har ikke en admin halløj så lad den bare altid blive vist i stedet.

**Comment by jakobwulfi** [comment]
Lav en metode der kan fjerne en elev/bruget fra et hold. Dette skal nok være en controller-metode. Når en bruger fjernes fra et fyldt hold med en venteliste, skal den første person i ventelisten tilføjes.
